version: '3'
services:
  bankas:
    image: webservisai/webservisai1:latest
    ports:
     - "80:5000"
    links:
     - rest:rest
    depends_on:
     - rest
  rest:
    image: webservisai/rest:latest
    ports:
      - "81:3000"
